services:
  axiom-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: axiom-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./data:/app/data

