[project]
name = "Axiom"
version = "0.1.0"
description = "A general purpose discord bot!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "colored>=2.3.0",
    "discord-py>=2.5.2",
    "dotenv>=0.9.9",
    "openai>=1.82.0",
    "pynacl>=1.5.0",
    "tinydb>=4.8.2",
]
